# Generated by Django 4.2.1 on 2023-05-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_groups_user_is_superuser_user_user_permissions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_superadmin",
        ),
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
